server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # proxy /api/* → backend Go
    location /api/ {
        proxy_pass http://mstf:8080/;
    }

    # fallback para Vue Router (history mode)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
